# Generated by Django 5.2.5 on 2025-08-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0002_alter_complaint_id_alter_grievance_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='Type_of_complaint',
        ),
        migrations.AddField(
            model_name='complaint',
            name='Type_of_addressee',
            field=models.CharField(choices=[('ClassRoom', 'ClassRoom'), ('Security', 'Security'), ('Management', 'Management'), ('College', 'College'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
