# Generated by Django 5.2.5 on 2025-08-27 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0003_remove_complaint_type_of_complaint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contactnumber',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
