# Generated by Django 5.2.5 on 2025-08-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0004_alter_profile_contactnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='Branch',
            field=models.CharField(choices=[('ClassRoom', 'ClassRoom'), ('Security', 'Security'), ('Management', 'Management'), ('College', 'College'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
